### ISSUE TITLE
Mattiols Reverse Proxy

### ISSUE THREAD

**Issue by djgragra** [andrea-mattioli/mattiols_hassio_repository#29]
Ciao, Sto ricevendo questo warning nel log di Home Assistant, può dipendere da Mattiols Reverse Proxy?

A request from a reverse proxy was received from 172.30.33.3, but your HTTP integration is not set-up for reverse proxies; This request will be blocked in Home Assistant 2021.7 unless you configure your HTTP integration to allow this header

Come posso risolvere?

**Comment by andrea-mattioli** [comment]
Come già detto,
non è un problema dell' addon del proxy, leggi la documentazione relativa ad HTTP: [https://www.home-assistant.io/integrations/http/](url)

```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```
